#!/bin/bash

# Tailscale Receiver Installer v2.2.1
# ==============================================================================
# Install Script for Tailscale File Receiver Service
#
# This script automates the process of installing the tailscale-receive.sh
# script as a systemd service, allowing it to run automatically on boot.
#
# It copies the script, leaving your original file untouched.
#
# Instructions:
# 1. Place this script in the SAME directory as your 'tailscale-receive.sh'.
# 2. Make this script executable: chmod +x install.sh
# 3. Run it with root privileges: sudo ./install.sh
# ==============================================================================

# Version information
readonly VERSION="2.2.1"

# Timer mode configuration
USE_TIMER="${USE_TIMER:-false}"  # Set to true to use systemd timer instead of looping service

# --- Configuration ---
# The original script that needs to be turned into a service.
SOURCE_SCRIPT="tailscale-receive.sh"
# Where the script will be copied to for system-wide access.
DEST_SCRIPT_PATH="/usr/local/bin/tailscale-receive.sh"
# The name of the systemd service we are creating.
SERVICE_NAME="tailscale-receive"
# The full path to the systemd service file.
SERVICE_FILE_PATH="/etc/systemd/system/${SERVICE_NAME}.service"

# Sender script and Service Menus
SEND_SOURCE_SCRIPT="tailscale-send.sh"
DEST_SEND_SCRIPT_PATH="/usr/local/bin/tailscale-send.sh"
SYS_KIO_SERVICEMENU_DIR="/usr/share/kio/servicemenus"
SYS_KSERVICES5_SERVICEMENU_DIR="/usr/share/kservices5/ServiceMenus"

# Nautilus (GNOME) integration
NAUTILUS_SCRIPTS_DIR="$HOME/.local/share/nautilus/scripts"
NAUTILUS_SCRIPT_NAME="Send to device using Tailscale"

# Environment file for configuration
ENV_FILE_PATH="/etc/default/tailscale-receive"

# --- Functions ---

# Function to print a formatted header
print_header() {
  echo "-----------------------------------------------------"
  echo "  $1"
  echo "-----------------------------------------------------"
}

# Function to print a success message
print_success() {
  echo "✅ $1"
}

# Function to print an error message and exit
print_error_and_exit() {
  echo "❌ ERROR: $1"
  exit 1
}

# Function to print a warning message
print_warning() {
  echo "⚠️  $1"
}

# Function to check if service is already installed
is_service_installed() {
  [ -f "$SERVICE_FILE_PATH" ] && systemctl is-enabled "$SERVICE_NAME.service" >/dev/null 2>&1
}

# Function to check if scripts are already installed
are_scripts_installed() {
  [ -f "$DEST_SCRIPT_PATH" ] || [ -f "$DEST_SEND_SCRIPT_PATH" ]
}

# Function to backup existing configuration
backup_existing_config() {
  local backup_dir="/tmp/tailscale-receiver-backup-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$backup_dir"

  if [ -f "$DEST_SCRIPT_PATH" ]; then
    cp "$DEST_SCRIPT_PATH" "$backup_dir/"
    echo "Backed up receiver script to $backup_dir/"
  fi

  if [ -f "$DEST_SEND_SCRIPT_PATH" ]; then
    cp "$DEST_SEND_SCRIPT_PATH" "$backup_dir/"
    echo "Backed up sender script to $backup_dir/"
  fi

  if [ -f "$SERVICE_FILE_PATH" ]; then
    cp "$SERVICE_FILE_PATH" "$backup_dir/"
    echo "Backed up service file to $backup_dir/"
  fi

  # Backup environment file if it exists
  backup_environment_file

  echo "Backup created at: $backup_dir"
}

# Function to create environment file
create_environment_file() {
  local target_user="$1"
  local target_dir="/home/$target_user/Downloads/tailscale"

  print_header "Creating Environment Configuration File"

  # Create directory if it doesn't exist
  mkdir -p "$(dirname "$ENV_FILE_PATH")" || {
    print_error_and_exit "Failed to create directory for environment file: $(dirname "$ENV_FILE_PATH")"
  }

  # Create environment file with proper permissions
  cat > "$ENV_FILE_PATH" << EOF
# Tailscale Receiver Configuration File
# This file contains configuration for the tailscale-receive service
# Generated by install.sh on $(date)

# Configuration version (automatically managed - do not modify)
CONFIG_VERSION="2.3.0"

# Target user for file ownership (required)
TARGET_USER=$target_user

# Target directory for received files (required)
TARGET_DIR=$target_dir

# Logging level: debug, info, warn, error
LOG_LEVEL=info

# Optional: Tailscale auth key for automatic authentication
# Obtain from: https://login.tailscale.com/admin/settings/keys
# TS_AUTHKEY=tskey-xxxxxxxxxxxxxxxxxx

# Optional: Archive management settings
# ARCHIVE_ENABLED=true
# ARCHIVE_DAYS=14
# ARCHIVE_DIR_NAME=archive

# Optional: Notification settings
# NOTIFY_TIMEOUT=10

# Optional: Polling and performance settings
# POLL_INTERVAL=15                    # Base polling interval (seconds)
# HEALTH_CHECK_INTERVAL=30            # Health check frequency (cycles)
# NETWORK_TIMEOUT=1                   # Network connectivity timeout (seconds)
# TAILSCALE_TIMEOUT=5                 # Tailscale status timeout (seconds)
# MAX_BACKOFF=300                     # Maximum backoff time (seconds)
# NOTIFICATION_THROTTLE=5             # Minimum seconds between notifications

# Optional: File integrity verification
# INTEGRITY_CHECK_ENABLED=false       # Enable/disable integrity checking
# INTEGRITY_CHECK_ALGORITHM=sha256    # Hash algorithm (sha256, sha512, md5)
# INTEGRITY_CHECK_TIMEOUT=30          # Timeout for integrity checks (seconds)
# INTEGRITY_CHECK_MAX_SIZE=1073741824 # Max file size for checks (1GB)

# Optional: Health endpoint for monitoring
# HEALTH_ENDPOINT_ENABLED=false       # Enable/disable health endpoint
# HEALTH_ENDPOINT_PORT=8080           # Port for health endpoint server
# HEALTH_ENDPOINT_PATH=/health        # Path for health checks

# Optional: File integrity verification (added in v2.3.0)
# INTEGRITY_CHECK_ENABLED=false       # Enable/disable integrity checking
# INTEGRITY_CHECK_ALGORITHM=sha256    # Hash algorithm (sha256, sha512, md5)
# INTEGRITY_CHECK_TIMEOUT=30          # Timeout for integrity checks (seconds)
# INTEGRITY_CHECK_MAX_SIZE=1073741824 # Max file size for checks (1GB)

# Optional: Polling and performance settings (added in v2.3.0)
# POLL_INTERVAL=15                    # Base polling interval (seconds)
# HEALTH_CHECK_INTERVAL=30            # Health check frequency (cycles)
# NETWORK_TIMEOUT=1                   # Network connectivity timeout (seconds)
# TAILSCALE_TIMEOUT=5                 # Tailscale status timeout (seconds)
# MAX_BACKOFF=300                     # Maximum backoff time (seconds)
# NOTIFICATION_THROTTLE=5             # Minimum seconds between notifications

# Optional: File type filtering and security (added in v2.3.0)
# FILE_FILTER_ENABLED=false           # Enable/disable file type filtering
# FILE_FILTER_MODE=allow              # allow/deny mode for filters
# FILE_FILTER_MIME_TYPES=             # Comma-separated allowed/denied MIME types
# FILE_FILTER_EXTENSIONS=             # Comma-separated allowed/denied extensions
# FILE_FILTER_MAX_SIZE=104857600      # Max file size for filtering (100MB)

# Optional: Virus scanning (added in v2.3.0)
# VIRUS_SCAN_ENABLED=false            # Enable/disable virus scanning
# VIRUS_SCAN_ENGINE=clamav            # Scanning engine
# VIRUS_SCAN_TIMEOUT=60               # Scan timeout (seconds)
# VIRUS_SCAN_QUARANTINE=false         # Quarantine infected files

# Optional: Rate limiting and abuse protection (added in v2.3.0)
# RATE_LIMIT_ENABLED=false            # Enable/disable rate limiting
# RATE_LIMIT_FILES_PER_MINUTE=60      # Max files per minute
# RATE_LIMIT_FILES_PER_HOUR=500       # Max files per hour
# RATE_LIMIT_SIZE_PER_MINUTE=104857600 # Max size per minute (100MB)
# RATE_LIMIT_SIZE_PER_HOUR=1073741824  # Max size per hour (1GB)
# RATE_LIMIT_BLOCK_DURATION=300       # Block duration in seconds
# RATE_LIMIT_RESET_INTERVAL=60        # Statistics reset interval
EOF

  # Set proper permissions (root:root, 600)
  chmod 600 "$ENV_FILE_PATH" || {
    print_error_and_exit "Failed to set permissions on environment file: $ENV_FILE_PATH"
  }

  chown root:root "$ENV_FILE_PATH" || {
    print_warning "Failed to set ownership on environment file (non-critical): $ENV_FILE_PATH"
  }

  print_success "Environment file created: $ENV_FILE_PATH"
  echo "  📝 Edit this file to customize settings:"
  echo "     sudo nano $ENV_FILE_PATH"
  echo "  🔒 File permissions: $(stat -c '%a %U:%G' "$ENV_FILE_PATH")"
}

# Function to backup environment file if it exists (called from backup_existing_config)
backup_environment_file() {
  if [ -f "$ENV_FILE_PATH" ]; then
    local backup_file="$backup_dir/$(basename "$ENV_FILE_PATH")"
    cp "$ENV_FILE_PATH" "$backup_file"
    echo "Backed up environment file to $backup_dir/"
  fi
}

# Function to create systemd timer unit
create_timer_unit() {
  local timer_file_path="/etc/systemd/system/${SERVICE_NAME}.timer"

  print_header "Creating Systemd Timer Unit"

  cat > "$timer_file_path" << EOL
[Unit]
Description=Tailscale File Receiver Timer
Documentation=https://github.com/1999AZZAR/tailscale_receiver
After=network-online.target tailscale.service
Wants=network-online.target

[Timer]
OnBootSec=30s
OnUnitActiveSec=30s
AccuracySec=1s
Persistent=true

[Install]
WantedBy=timers.target
EOL

  print_success "Timer unit created at '$timer_file_path'."
}

# Function to create service unit for timer mode
create_timer_service_unit() {
  print_header "Creating Timer Service Unit"

  cat > "$SERVICE_FILE_PATH" << EOL
[Unit]
Description=Tailscale File Receiver (Timer Mode)
Documentation=https://github.com/1999AZZAR/tailscale_receiver
After=network-online.target tailscale.service
Wants=network-online.target

[Service]
Type=oneshot
User=root
Group=root
EnvironmentFile=-$ENV_FILE_PATH
ExecStart=$DEST_SCRIPT_PATH --once
TimeoutSec=300

# Security hardening - temporarily reduced for compatibility
# PrivateTmp=true
# ProtectSystem=strict
# ProtectHome=yes
ReadWritePaths=/home/%i/Downloads/tailscale
# NoNewPrivileges=true
# ProtectHostname=true
# ProtectClock=true
# ProtectControlGroups=true
# ProtectKernelTunables=true
# RestrictSUIDSGID=true
# LockPersonality=true
# RestrictRealtime=true
# SystemCallFilter=@system-service @file-system
# CapabilityBoundingSet=
EOL

  print_success "Timer service unit created at '$SERVICE_FILE_PATH'."
}

# Function to create Nautilus script for GNOME integration
create_nautilus_script() {
  local script_path="$NAUTILUS_SCRIPTS_DIR/$NAUTILUS_SCRIPT_NAME"

  # Create Nautilus scripts directory if it doesn't exist
  mkdir -p "$NAUTILUS_SCRIPTS_DIR" || {
    print_warning "Failed to create Nautilus scripts directory: $NAUTILUS_SCRIPTS_DIR"
    return 1
  }

  # Create the Nautilus script
  cat > "$script_path" << 'EOF'
#!/bin/bash
# Nautilus script to send files using Tailscale
# This script is called with selected files as arguments

# Check if any files were selected
if [ $# -eq 0 ]; then
    zenity --error --title="Tailscale Send" --text="No files selected." 2>/dev/null || \
    echo "Error: No files selected." >&2
    exit 1
fi

# Check if tailscale-send.sh exists and is executable
if [ ! -x "/usr/local/bin/tailscale-send.sh" ]; then
    zenity --error --title="Tailscale Send" --text="Tailscale sender not found. Please reinstall the tailscale-receiver package." 2>/dev/null || \
    echo "Error: Tailscale sender not found. Please reinstall the tailscale-receiver package." >&2
    exit 1
fi

# Call the tailscale sender with all selected files
exec /usr/local/bin/tailscale-send.sh "$@"
EOF

  # Make the script executable
  chmod +x "$script_path" || {
    print_warning "Failed to make Nautilus script executable: $script_path"
    return 1
  }

  print_success "Nautilus script created: $script_path"
}

# Function to perform preflight checks
preflight_checks() {
  echo "🔍 Performing preflight checks..."

  local issues_found=0

  # Check for root privileges
  if [ "$EUID" -ne 0 ]; then
    echo "❌ ERROR: This script must be run as root. Please use 'sudo ./install.sh'"
    echo "   Solution: sudo ./install.sh"
    exit 1
  fi

  # Check for systemd
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "❌ ERROR: systemd is required but not found."
    echo "   This script requires a systemd-based Linux distribution."
    echo "   Compatible systems: Ubuntu, Debian, Fedora, Arch, CentOS, etc."
    exit 1
  fi

  # Check for Tailscale
  if ! command -v tailscale >/dev/null 2>&1; then
    echo "❌ ERROR: Tailscale is not installed."
    echo "   Please install Tailscale first:"
    echo "   - Ubuntu/Debian: curl -fsSL https://tailscale.com/install.sh | sh"
    echo "   - Other systems: Visit https://tailscale.com/download"
    exit 1
  fi

  # Check Tailscale status
  if ! tailscale status >/dev/null 2>&1; then
    echo "⚠️  WARNING: Tailscale is installed but not logged in."
    echo "   The service will install successfully, but you'll need to authenticate:"
    echo "   sudo tailscale up"
    echo "   Or set TS_AUTHKEY environment variable for automated setup."
    echo ""
    ((issues_found++))
  else
    echo "✅ Tailscale is installed and authenticated"
  fi

  # Check for notify-send (optional but recommended)
  if ! command -v notify-send >/dev/null 2>&1; then
    echo "⚠️  WARNING: notify-send not found (desktop notifications disabled)."
    echo "   Install libnotify-bin (Ubuntu/Debian) for desktop notifications."
    echo "   This is optional - the service will work without it."
    echo ""
  else
    echo "✅ Desktop notifications available"
  fi

  # Check for required tools
  local required_tools=("ping" "chown" "runuser")
  for tool in "${required_tools[@]}"; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      echo "❌ ERROR: Required tool '$tool' not found."
      echo "   This tool is usually part of the base system. Please check your installation."
      exit 1
    fi
  done

  # Check for GUI tools (optional)
  local gui_tools=("kdialog" "zenity" "whiptail")
  local gui_available=false
  for tool in "${gui_tools[@]}"; do
    if command -v "$tool" >/dev/null 2>&1; then
      gui_available=true
      break
    fi
  done

  if [ "$gui_available" = false ]; then
    echo "⚠️  WARNING: No GUI dialog tools found (kdialog, zenity, whiptail)."
    echo "   The sender script will fall back to command-line interface."
    echo "   Install 'kdialog' (KDE), 'zenity' (GNOME), or 'whiptail' (console) for better UX."
    echo ""
  else
    echo "✅ GUI dialog tools available"
  fi

  # Check for desktop environments and file managers
  local nautilus_available=false
  if command -v nautilus >/dev/null 2>&1; then
    nautilus_available=true
    echo "✅ Nautilus (GNOME) detected - will install context menu integration"
  fi

  local dolphin_available=false
  if command -v dolphin >/dev/null 2>&1; then
    dolphin_available=true
    echo "✅ Dolphin (KDE) detected - will install context menu integration"
  fi

  if [ "$nautilus_available" = false ] && [ "$dolphin_available" = false ]; then
    echo "ℹ️  INFO: No supported file managers detected (Nautilus/Dolphin)."
    echo "   Context menu integration will be skipped."
    echo "   You can still use the command-line sender: /usr/local/bin/tailscale-send.sh"
    echo ""
  fi

  # Check if target directories are writable (simulate what the script will do)
  local test_user
  if [[ -n "${TARGET_USER:-}" ]]; then
    test_user="$TARGET_USER"
  elif [[ -n "${SUDO_USER:-}" ]]; then
    test_user="$SUDO_USER"
  else
    test_user="root"
  fi

  if id "$test_user" &>/dev/null; then
    local test_dir="/home/$test_user/Downloads"
    if [[ -d "$test_dir" ]]; then
      if [[ -w "$test_dir" ]]; then
        echo "✅ Target directory structure looks good: $test_dir"
      else
        echo "⚠️  WARNING: Target directory not writable: $test_dir"
        echo "   The service may fail to create the tailscale subdirectory."
        echo "   Check permissions: ls -ld $test_dir"
        ((issues_found++))
      fi
    else
      echo "⚠️  WARNING: Downloads directory doesn't exist: $test_dir"
      echo "   It will be created during installation."
    fi
  fi

  # Check for existing installation
  if [ -f "$SERVICE_FILE_PATH" ] || [ -f "$DEST_SCRIPT_PATH" ] || [ -f "$ENV_FILE_PATH" ]; then
    echo "ℹ️  Existing installation detected."
    echo "   A backup will be created during installation."
  fi

  # Check available disk space
  local available_space
  available_space=$(df /usr/local | awk 'NR==2 {print int($4/1024)}')  # KB to MB
  if [[ $available_space -lt 50 ]]; then
    echo "⚠️  WARNING: Low disk space available: ${available_space}MB"
    echo "   At least 50MB recommended for installation and logs."
    ((issues_found++))
  fi

  # Summary
  if [ $issues_found -eq 0 ]; then
    echo "✅ All preflight checks passed!"
  else
    echo "⚠️  $issues_found issue(s) found. Review warnings above."
    echo "   Installation can proceed but may have limited functionality."
  fi

  echo ""
}

# Function to validate user
validate_user() {
  local user="$1"

  # Check if user exists
  if ! id "$user" &>/dev/null; then
    print_error_and_exit "User '$user' does not exist"
  fi

  # Check if user has a home directory
  local user_home
  user_home=$(getent passwd "$user" | cut -d: -f6)
  if [[ -z "$user_home" || ! -d "$user_home" ]]; then
    print_error_and_exit "User '$user' does not have a valid home directory"
  fi

  # Check if Downloads directory exists or can be created
  local downloads_dir="$user_home/Downloads"
  if [[ ! -d "$downloads_dir" ]]; then
    if ! mkdir -p "$downloads_dir" 2>/dev/null; then
      print_error_and_exit "Cannot create Downloads directory for user '$user'"
    fi
    # Restore ownership
    chown "$user:$user" "$downloads_dir"
  fi

  # Verify we can write to the target directory
  local target_dir="$downloads_dir/tailscale"
  if [[ ! -d "$target_dir" ]]; then
    if ! mkdir -p "$target_dir" 2>/dev/null; then
      print_error_and_exit "Cannot create tailscale directory in Downloads for user '$user'"
    fi
  fi

  # Test write permissions
  if ! touch "$target_dir/.install_test" 2>/dev/null; then
    print_error_and_exit "No write permissions to '$target_dir'"
  fi
  rm -f "$target_dir/.install_test"

  # Restore ownership
  chown -R "$user:$user" "$target_dir"
}

# Function to get the target user
get_target_user() {
  local default_user=""
  
  # Try to get the user who ran sudo
  if [ -n "$SUDO_USER" ]; then
    default_user="$SUDO_USER"
  else
    # Fallback to the first non-root user with a home directory
    default_user=$(find /home -maxdepth 1 -type d -name "*" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "")
  fi
  
  if [ -z "$default_user" ]; then
    print_error_and_exit "Could not determine default user. Please specify manually."
  fi
  
  if [ "${NONINTERACTIVE:-false}" = "true" ]; then
    echo "$default_user"
    return
  fi
  
  echo "" >&2
  echo "Which user should receive the Tailscale files?" >&2
  echo "This user will:" >&2
  echo "  - Own the received files" >&2
  echo "  - Receive desktop notifications" >&2
  echo "  - Have files saved to their Downloads/tailscale/ directory" >&2
  echo "" >&2
  
  while true; do
    read -r -p "Enter username [$default_user]: " target_user
    target_user=${target_user:-$default_user}
    
    # Validate the user exists
    if id "$target_user" &>/dev/null; then
      echo "" >&2
      echo "✅ User '$target_user' found." >&2
      break
    else
      echo "❌ User '$target_user' does not exist. Please try again." >&2
    fi
  done
  
  echo "$target_user"
}

# Function to create and configure the receiver script
create_receiver_script() {
  local target_user="$1"
  local target_dir="/home/$target_user/Downloads/tailscale"

  # Create the target directory and set ownership
  mkdir -p "$target_dir"
  chown "$target_user:$target_user" "$target_dir"

  # Copy the script without modification (configuration via environment file)
  install -m 0755 "$SOURCE_SCRIPT" "$DEST_SCRIPT_PATH" || {
    print_error_and_exit "Failed to install receiver script to '$DEST_SCRIPT_PATH'"
  }
}

# Function to show interactive setup wizard
show_setup_wizard() {
  echo "🚀 Welcome to Tailscale Receiver Setup Wizard!"
  echo ""
  echo "This wizard will help you set up automated file receiving via Tailscale."
  echo "The service will automatically accept files sent to your device."
  echo ""
  echo "📋 What this setup will do:"
  echo "  • Install a background service that monitors for incoming files"
  echo "  • Set up automatic file ownership correction"
  echo "  • Configure desktop notifications (if available)"
  echo "  • Install a sender script for easy file sharing"
  echo "  • Add Dolphin (KDE) right-click integration"
  echo ""
  echo "📁 Files will be saved to: ~/Downloads/tailscale/"
  echo "🔐 Requires Tailscale to be installed and authenticated"
  echo ""

  if [ "${NONINTERACTIVE:-false}" != "true" ]; then
    read -r -p "Continue with setup? (Y/n): " setup_confirm
    case "$setup_confirm" in
      [Nn]|[Nn][Oo])
        echo "Setup cancelled. You can run this again anytime."
        exit 0
        ;;
      *)
        echo "Starting setup..."
        ;;
    esac
  fi

  echo ""
}

# --- Script Logic ---

print_header "Tailscale Receiver Service Install"

# Handle version flag
if [[ "${1:-}" == "--version" ]] || [[ "${1:-}" == "-v" ]]; then
  echo "Tailscale Receiver Installer v${VERSION}"
  exit 0
fi

# Show setup wizard for interactive installs
if [ "${NONINTERACTIVE:-false}" != "true" ]; then
  show_setup_wizard
fi

# 1. Perform preflight checks
preflight_checks

# 2. Check if the source script exists in the current directory
if [ ! -f "$SOURCE_SCRIPT" ]; then
  print_error_and_exit "The source script '$SOURCE_SCRIPT' was not found. Make sure it's in the same directory as this Install script."
fi

# 3. Get the target user
TARGET_USER=$(get_target_user)
echo "Target user: $TARGET_USER"

# 4. Validate the target user and their environment
echo "➡️  Validating user configuration..."
validate_user "$TARGET_USER"
print_success "User '$TARGET_USER' validation passed."

# 5. Check for existing installation and handle reinstallation
if is_service_installed || are_scripts_installed; then
  echo ""
  print_warning "Existing Tailscale Receiver installation detected!"
  echo ""
  echo "Found existing installation:"
  if [ -f "$DEST_SCRIPT_PATH" ]; then
    echo "  ✅ Receiver script: $DEST_SCRIPT_PATH"
  fi
  if [ -f "$DEST_SEND_SCRIPT_PATH" ]; then
    echo "  ✅ Sender script: $DEST_SEND_SCRIPT_PATH"
  fi
  if [ -f "$SERVICE_FILE_PATH" ]; then
    echo "  ✅ Service file: $SERVICE_FILE_PATH"
  fi
  echo ""
  
  # Determine installation mode
  if [ "${NONINTERACTIVE:-false}" = "true" ]; then
    echo "Non-interactive mode: Proceeding with update..."
    backup_existing_config
    choice=1
  else
    echo "Choose an option:"
    echo "  1) Update/Reinstall (recommended) - Backup existing config and install new version"
    echo "  2) Fresh Install - Remove existing installation completely"
    echo "  3) Cancel"
    echo ""
    read -r -p "Enter your choice (1-3): " choice
  fi
  
  # Handle the choice
  case $choice in
    1)
      echo "Proceeding with update/reinstall..."
      backup_existing_config
      ;;
    2)
      echo "Proceeding with fresh install..."
      echo "Stopping and removing existing service..."
      systemctl stop "$SERVICE_NAME.service" 2>/dev/null || true
      systemctl disable "$SERVICE_NAME.service" 2>/dev/null || true
      rm -f "$SERVICE_FILE_PATH"
      rm -f "$DEST_SCRIPT_PATH"
      rm -f "$DEST_SEND_SCRIPT_PATH"
      rm -f "$SYS_KIO_SERVICEMENU_DIR/tailscale-send.desktop"
      rm -f "$SYS_KSERVICES5_SERVICEMENU_DIR/tailscale-send.desktop"
      systemctl daemon-reload
      ;;
    3)
      echo "Installation cancelled."
      exit 0
      ;;
    *)
      print_error_and_exit "Invalid choice. Please run the script again."
      ;;
  esac
  echo ""
fi

# 6. Create and configure the receiver script
echo "➡️  Installing the receiver script..."
create_receiver_script "$TARGET_USER"
print_success "Receiver script installed to '$DEST_SCRIPT_PATH'."

# 6. Create environment configuration file
create_environment_file "$TARGET_USER"

# 7. Install the sender script (for Dolphin context menu)
if [ -f "$SEND_SOURCE_SCRIPT" ]; then
  echo "➡️  Installing the sender script..."
  install -m 0755 "$SEND_SOURCE_SCRIPT" "$DEST_SEND_SCRIPT_PATH" || print_error_and_exit "Failed to install sender script to '$DEST_SEND_SCRIPT_PATH'."
  print_success "Sender script installed to '$DEST_SEND_SCRIPT_PATH'."
else
  echo "⚠️  Sender script '$SEND_SOURCE_SCRIPT' not found. Skipping send integration."
fi

# 8. Create the systemd service/timer files
if [[ "$USE_TIMER" == "true" ]]; then
  echo "➡️  Creating systemd timer and service files for power-efficient operation..."
  create_timer_service_unit
  create_timer_unit
else
  echo "➡️  Creating systemd service file with security hardening..."
  cat > "$SERVICE_FILE_PATH" << EOL
[Unit]
Description=Tailscale File Receiver Service
Documentation=https://github.com/your-repo (optional)
After=network-online.target tailscale.service
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
EnvironmentFile=-$ENV_FILE_PATH
ExecStart=$DEST_SCRIPT_PATH
Restart=on-failure
RestartSec=15s

# Security hardening - temporarily reduced for compatibility
# PrivateTmp=true
# ProtectSystem=strict
# ProtectHome=yes
ReadWritePaths=/home/$TARGET_USER/Downloads/tailscale
# NoNewPrivileges=true
# ProtectHostname=true
# ProtectClock=true
# ProtectControlGroups=true
# ProtectKernelTunables=true
# RestrictSUIDSGID=true
# LockPersonality=true
# RestrictRealtime=true
# SystemCallFilter=@system-service @file-system
# CapabilityBoundingSet=
EOL
  print_success "Service file created at '$SERVICE_FILE_PATH'."
fi

# 9. Reload systemd and activate service/timer
echo "➡️  Activating the service..."
systemctl daemon-reload

if [[ "$USE_TIMER" == "true" ]]; then
  systemctl enable "$SERVICE_NAME.timer" || print_error_and_exit "Failed to enable the timer."
  systemctl start "$SERVICE_NAME.timer" || print_error_and_exit "Failed to start the timer."
  print_success "Timer has been enabled and started."
  echo "  📊 Service will run every 30 seconds when active"
  echo "  🔋 Power-efficient mode reduces CPU usage when idle"
else
  systemctl enable "$SERVICE_NAME.service" || print_error_and_exit "Failed to enable the service."
  systemctl start "$SERVICE_NAME.service" || print_error_and_exit "Failed to start the service."
  print_success "Service has been enabled and started."
  echo "  🔄 Service runs continuously in background"
fi

# 10. Install Dolphin service menu entries (system-wide)
if [ -f "$DEST_SEND_SCRIPT_PATH" ]; then
  echo "➡️  Installing Dolphin service menu..."
  mkdir -p "$SYS_KIO_SERVICEMENU_DIR" "$SYS_KSERVICES5_SERVICEMENU_DIR"

  # Create desktop service menu file
  DESKTOP_CONTENT='[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/allfiles;inode/directory;
Actions=TailScaleSend;

[Desktop Action TailScaleSend]
Name=Send to device using Tailscale
Icon=network-workgroup
Exec=/usr/local/bin/tailscale-send.sh %F
'

  # Create temporary file and install it
  TMP_DESKTOP_FILE=$(mktemp) || print_error_and_exit "Failed to create temporary file for desktop menu."
  echo "$DESKTOP_CONTENT" > "$TMP_DESKTOP_FILE" || print_error_and_exit "Failed to write desktop content to temporary file."

  install -m 0644 "$TMP_DESKTOP_FILE" "$SYS_KIO_SERVICEMENU_DIR/tailscale-send.desktop" || print_error_and_exit "Failed to install service menu (.kio)."
  install -m 0644 "$TMP_DESKTOP_FILE" "$SYS_KSERVICES5_SERVICEMENU_DIR/tailscale-send.desktop" || print_error_and_exit "Failed to install service menu (kservices5)."

  rm -f "$TMP_DESKTOP_FILE"
  print_success "Dolphin service menu installed."

  # Rebuild KDE service cache if tools exist
  if command -v kbuildsycoca6 >/dev/null 2>&1; then
    kbuildsycoca6 >/dev/null 2>&1 || true
  elif command -v kbuildsycoca5 >/dev/null 2>&1; then
    kbuildsycoca5 >/dev/null 2>&1 || true
  fi
fi

# 10. Install Nautilus integration (GNOME)
if command -v nautilus >/dev/null 2>&1; then
  echo "➡️  Installing Nautilus (GNOME) integration..."
  if create_nautilus_script; then
    print_success "Nautilus integration installed."
    echo "  📁 Right-click files/folders in Nautilus → Scripts → 'Send to device using Tailscale'"
  else
    print_warning "Nautilus integration installation failed."
  fi
else
  echo "⏭️  Skipping Nautilus integration (Nautilus not found)."
fi

# 11. Final status check and confirmation
echo ""
print_header "Install Complete!"
echo "The Tailscale receiver service is now running and will start on boot."
echo ""
echo "📋 Installation Summary:"
echo "  ✅ Receiver script: $DEST_SCRIPT_PATH"
echo "  ✅ Target user: $TARGET_USER"
echo "  ✅ Target directory: /home/$TARGET_USER/Downloads/tailscale/"
if [ -f "$DEST_SEND_SCRIPT_PATH" ]; then
  echo "  ✅ Sender script: $DEST_SEND_SCRIPT_PATH"
  echo "  ✅ Dolphin service menu: Installed"
fi
echo "  ✅ Systemd service: $SERVICE_NAME.service"
echo ""
echo "🔧 Management Commands:"
echo "  Check service status: sudo systemctl status $SERVICE_NAME.service"
echo "  View live logs: sudo journalctl -u $SERVICE_NAME.service -f"
echo "  Stop service: sudo systemctl stop $SERVICE_NAME.service"
echo "  Start service: sudo systemctl start $SERVICE_NAME.service"
echo "  Restart service: sudo systemctl restart $SERVICE_NAME.service"
echo ""
echo "📁 Test the installation:"
if [ -f "$DEST_SEND_SCRIPT_PATH" ]; then
  echo "  Send a file: $DEST_SEND_SCRIPT_PATH /path/to/file"
fi
echo "  Check received files in: /home/$TARGET_USER/Downloads/tailscale/"
echo ""
echo "🔄 To update/reinstall: Run this script again"
echo "🗑️  To uninstall: sudo ./uninstall.sh"
echo "-----------------------------------------------------"

